# Generated by Django 4.2.6 on 2023-10-31 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Addcar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('is_available', models.CharField(default=True, max_length=100)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.categorymodel')),
            ],
        ),
    ]
