# Generated by Django 4.2.6 on 2023-10-31 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_point', models.CharField(max_length=100)),
                ('destination_point', models.CharField(max_length=100)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('car_type', models.CharField(choices=[('Tata Zest', 'Tata Zest'), ('Maruti Dzire', 'Maruti Dzire'), ('Swift Dzire', 'Swift Dzire'), ('Toyota Etios', 'Toyota Etios'), ('Toyota Innova', 'Toyota Innova'), ('Maruti Ertiga', 'Maruti Ertiga'), ('Hyundai Xcent', 'Hyundai Xcent')], max_length=50)),
                ('no_of_persons', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('is_confirmed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
