# Generated by Django 4.2.6 on 2023-10-31 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Car', '0002_booking_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='carbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_point', models.CharField(max_length=100)),
                ('destination_point', models.CharField(max_length=100)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('car_type', models.CharField(choices=[('Tata Zest', 'Tata Zest'), ('Maruti Dzire', 'Maruti Dzire'), ('Swift Dzire', 'Swift Dzire'), ('Toyota Etios', 'Toyota Etios'), ('Toyota Innova', 'Toyota Innova'), ('Maruti Ertiga', 'Maruti Ertiga'), ('Hyundai Xcent', 'Hyundai Xcent')], max_length=50)),
                ('no_of_persons', models.IntegerField()),
                ('is_confirmed', models.BooleanField(default=True)),
                ('addcar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_booking', to='Car.addcar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
