# Generated by Django 4.2.6 on 2023-11-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
