# Generated by Django 4.2.6 on 2023-11-02 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0005_remove_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='car_type',
        ),
        migrations.AddField(
            model_name='carbooking',
            name='contact',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carbooking',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carbooking',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
