# Generated by Django 4.2.6 on 2023-11-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0006_remove_carbooking_car_type_carbooking_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='total_rent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
