# Generated by Django 4.2.6 on 2023-11-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0007_carbooking_total_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='total_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
