# Generated by Django 4.2.6 on 2023-11-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0008_alter_carbooking_total_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='total_rent',
        ),
    ]
