# Generated by Django 4.2.6 on 2023-11-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0010_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
