# Generated by Django 4.2.6 on 2023-11-07 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0012_alter_addcar_capacity_alter_addcar_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcar',
            name='rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
