# Generated by Django 4.2.6 on 2023-11-07 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0013_alter_addcar_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcar',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='no_of_persons',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
