# Generated by Django 4.2.6 on 2023-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0014_alter_addcar_capacity_alter_carbooking_no_of_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcar',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
