# Generated by Django 4.2.6 on 2023-11-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0015_alter_addcar_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='no_of_persons',
            field=models.IntegerField(),
        ),
    ]
